spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employees
    username: root
    password: jaymysql

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: ALWAYS


#  cache:
#    type: redis

#  redis:
#    host: localhost
#    port: 6379